apiVersion: v1
kind: Pod
metadata:
       name: pod-with-port80
       labels:
         type: mytype
spec:
       containers:
               - name: expressjs
                 image: mohsinkhalid/expressjs
                 ports: 
                  - containerPort: 80 

 
  
