#hostpath volume 

apiVersion: v1
kind: Pod
metadata: 
 name: redis-hostpath2
spec:
 containers: 
  - name: redis-container
    image: redis
    volumeMounts:
     - mountPath: /test-mnt
       name: test-vol2
 volumes: 
  - name: test-vol2
    hostPath: 
     path: /home/ashar/Documents/kubernetes-volumes

