# this yaml file is for emptyDir pod 

apiVersion: v1

kind: Pod
metadata: 
 name: test-ed 


spec:
 containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - name: cache-volume     # name of the volume/directory which is to be mounted in the pod 
      mountPath: /cache      # data will be saved/mounted to this directory in the pod 
 volumes:
  - name: cache-volume
    emptyDir: {}

