apiVersion: v1
kind: PersistentVolume
metadata: 
 name: assignment-pv
spec:
 accessModes:
  - ReadWriteOnce
 capacity:
  storage: 2M
 
 hostPath:
  path: /tmp/assignment
 
 storageClassName: fast

 persistentVolumeReclaimPolicy: Delete 

