apiVersion: apps/v1
kind: Deployment
metadata:
 name: assignment-deployment
 labels:
  app: frontend

spec: 
 replicas: 10
 selector:
  matchLabels:
   app: frontend

 template:
  metadata:
   labels:
    app: frontend
  spec:

   volumes:
    - name: assignment-vol
      persistentVolumeClaim: 
       claimName: assignment-pvc  

   containers:
    - name: frontend-container
      image: corneredtiger/html-app
      
      volumeMounts:
       - name: assignment-vol 
         mountPath: /data 

      ports:
       - containerPort: 80 
      
      livenessProbe:
       httpGet:
        path: /
        port: 80 
      
       failureThreshold: 2
       periodSeconds: 15 
       successThreshold: 1
       timeoutSeconds: 2 
       initialDelaySeconds: 15 


      readinessProbe: 
       httpGet:
        port: 80
        path: /
